version: 2
jobs:
  flake8:
    working_directory: ~/wagtail-autocomplete-repo
    docker:
      - image: randomknowledge/docker-pyenv-tox
    steps:
      - checkout
      - run:
          name: flake8
          command: tox -e flake8
  tests:
    working_directory: ~/wagtail-autocomplete-repo
    docker:
      - image: randomknowledge/docker-pyenv-tox
    steps:
      - checkout
      - run:
          name: tests
          command: tox

workflows:
  version: 2
  autocomplete_ci:
    jobs:
      - tests
      - flake8
